[build]
builder = "DOCKERFILE"
dockerfilePath = ".wasp/build/Dockerfile"

[deploy]
startCommand = "cd .wasp/build/server && npm run start-production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
